# Generated by Django 5.0.3 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammember_created_at_teammember_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
